Build base html for home1
st-vietnguyen/FE-Intership-2023_Viet-Nguyen-T_FE-Exercise pull request #7
Opened 2023-08-04 09:09 UTC by st-vietnguyen

### Description
Build base html for home1 design

### Checklist
- [X] App run correctly
- [X] The code has been tested in the local environment.
- [X] No convention errors

2023-08-05 04:16 UTC, st-quangnguyen2 commented on index.html
> +    <head>
đầu tiên `convention` của team mình là `indent tab 2` em config format lại chỗ này

2023-08-05 04:21 UTC, st-quangnguyen2 commented on index.html
> +                    </ul>
thêm giúp anh `class` cho `a`

2023-08-05 04:27 UTC, st-quangnguyen2 requested changes
@st-vietnguyen check cmts
update convention và thêm class cho các thẻ giúp anh

2023-08-06 16:23 UTC, st-quangnguyen2 commented on index.html
> +    </head>
`title` để tên của page

2023-08-06 16:23 UTC, st-quangnguyen2 commented on index.html
> +                </div>
ở bài tập này mình dùng `h1` để bọc `logo`

2023-08-06 16:24 UTC, st-quangnguyen2 commented on index.html
> +                </div>
icon dùng thẻ `i` và thêm class cho nó

2023-08-06 16:25 UTC, st-quangnguyen2 commented on index.html
> +                <div class="overlay"></div>
`section` sẽ có class `section section-{...}` -> `section section-banner` tương tự với các `section` còn lại

2023-08-06 16:26 UTC, st-quangnguyen2 commented on index.html
> +                    <a class="banner-link">
`h1` đã dùng cho logo nên em dùng thẻ khác thay thế, thêm class cho nó

2023-08-06 16:27 UTC, st-quangnguyen2 commented on index.html
> +                <div class="banner-title">
`banner-title` -> `section-title`
đọc lại bài sharing của anh trong channel

2023-08-06 16:30 UTC, st-quangnguyen2 commented on index.html
> +                        </div>
1. tại sao lại cần `div` bọc ở đây
2. tại sao `title` lại nằm trong `description`
3. `text` -> `desc`, `span` -> `p`
4. `h3` -> `h4`
5. thêm class cho thẻ `i`

2023-08-06 16:31 UTC, st-quangnguyen2 commented on index.html
> +            </section>
cái này nó đang ở dạng list nhưng anh lại không thấy sử dụng `ul li`
thêm class cho section

2023-08-06 16:32 UTC, st-quangnguyen2 commented on index.html
> +            <section class="products">
thêm class cho `section`, `section section-products`

2023-08-06 16:33 UTC, st-quangnguyen2 commented on index.html
> +                        <img src="" alt="" />
thêm class cho `img`

2023-08-06 16:34 UTC, st-quangnguyen2 commented on index.html
> +            <footer class="footer">
cái này là một `section`, `div` -> `section`, thêm class cho section

2023-08-06 16:35 UTC, st-quangnguyen2 commented on index.html
> +                        </div>
cái này là một `list` dùng `ul li` và `a` bọc `i`, không có ngược lại

2023-08-06 16:37 UTC, st-quangnguyen2 commented on index.html
> +                    </div>
nếu em để ý sẽ thấy rằng các item ở đây đều link tới một trang khác, vì thế mình sẽ có thêm thẻ `a` bên trong `li`, nhớ thêm class cho nó

2023-08-06 16:38 UTC, st-quangnguyen2 commented on index.html
> +                    </span>
`span` -> `p`

2023-08-06 16:39 UTC, st-quangnguyen2 requested changes
@st-vietnguyen check cmts

2023-08-07 12:21 UTC, st-manhle requested changes

2023-08-07 12:21 UTC, st-manhle commented on index.html
> +          <img src="./images/logo.svg" alt="logo" class="header-logo-image" />
alt của img logo = title của web e nha, mục đích tăng SEO

2023-08-07 12:21 UTC, st-manhle commented on index.html
> +        <ul class="nav-menu">
thêm 1 class là nav-list nha

2023-08-07 12:21 UTC, st-manhle commented on index.html
> +      <div class="header-icons">
đây là header-actions  chứ k phải icon e nha
Dùng ul-li nhé

2023-08-07 12:21 UTC, st-manhle commented on index.html
> +              <a href="" class="product-item-link">
đặt tên ngắn gọn xúc tích e nghe, gợi ý: product-link

2023-08-08 06:47 UTC, st-quangnguyen2 approved these changes

2023-08-08 06:47 UTC, merged